services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: valentine-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - PYTHON_VERSION=3.12
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data  # монтируем папку с базой данных
    network_mode: bridge